template: |

  Toi qui va release : Mode d\'emploi ici : https://github.com/friends-of-presta/fop_console/blob/dev/docs/RELEASE.md
  En rÃ©sumÃ© :
  - modifie et copie ce contenu (1)
  - ne publie pas !
  - pousse un tag sur le dÃ©pot
  - Ã§a a gÃ©nÃ©rÃ© une release : modifie lÃ  pour y coller le texte copiÃ© en (1)
  - efface cette notice
  - publie !

  ## Whatâ€™s New
  $CHANGES

tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature'
  - title: 'âœ… Enhancements'
    label: 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    label: 'bug'
  - title: 'ğŸ“• Documentation'
    label: 'documentation'
